import Head from 'next/head'
import MainCard from '../components/main-card.js'
import Navigation from '../components/navigation'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Travel Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="centered">
        <Navigation />
        <MainCard />
      </div>
      
    </div>
  )
}
