import Head from 'next/head'
import MainCard from '../components/main-card.js'
import Navigation from '../components/navigation'
import data from '../data/data.js'

export default function Home() {

  const cardObject = data.map(item => {
    return <MainCard 
      id = {item.id}
      map = {item.map}
      title = {item.title}
      alt = {item.alt}
      description = {item.description}
      />

  })

  return (
    <div>
      <Head>
        <title>Travel Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="centered">
        <Navigation />
        {cardObject}
      </div>
      
    </div>
  )
}
